### ISSUE TITLE
关于您的仓库Token-Path-Prediction

### ISSUE THREAD

**Issue by WinterShiver** [BeyondYourself/llm_babyCare#1]
您好，我是仓库[Token-Path-Prediction](https://github.com/BeyondYourself/Token-Path-Prediction)的作者；这个仓库无法提issue，所以出于无奈在您的另一个仓库提出issue联系。恳请您看到issue后通过邮箱zc231214@hotmail.com联系我，谢谢！

**Comment by BeyondYourself** [comment]
> 您好，我是仓库[Token-Path-Prediction](https://github.com/BeyondYourself/Token-Path-Prediction)的作者；这个仓库无法提issue，所以出于无奈在您的另一个仓库提出issue联系。恳请您看到issue后通过邮箱[zc231214@hotmail.com](mailto:zc231214@hotmail.com)联系我，谢谢！

你好，是有什么事情吗，无法提issue是怎么回事

**Comment by WinterShiver** [comment]
> > 您好，我是仓库[Token-Path-Prediction](https://github.com/BeyondYourself/Token-Path-Prediction)的作者；这个仓库无法提issue，所以出于无奈在您的另一个仓库提出issue联系。恳请您看到issue后通过邮箱[zc231214@hotmail.com](mailto:zc231214@hotmail.com)联系我，谢谢！
> 
> 你好，是有什么事情吗，无法提issue是怎么回事

这个仓库没有issue button. 恳请您尽快联系我，也可以通过添加我的微信联系，微信号：zc314214. 谢谢！
